### ISSUE TITLE
Stream is not cluster ready

### ISSUE THREAD

**Issue by To-om** [TheHive-Project/elastic4play#41]
The Stream system allows different components to transmit messages (add, remove, update an entity for example) on a bus.
Currently, the messages sent to the Stream have a local scope: they are not transmitted to other application nodes when it run in cluster.
The aim of this issue is to make Stream cluster ready: the messages are transmitted to all application nodes, as if each component was on the same node.

**Comment by ParanoidRat** [comment]
@To-om, I guess this explains why I observed [#414](https://github.com/TheHive-Project/TheHive/issues/414) in TheHive, right?

**Comment by To-om** [comment]
@ParanoidRat Yes, stream system is not aware of other cluster nodes yet.
