### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by srilumpa** [TheHive-Project/elastic4play#56]
Hi,

We recently configured our Elasticsearch cluster to handle SSL transport. Unfortunately, we noticed that the elastic4play framework does not support it and we were forced to rollback our configuration.

I am going to try to implement the SSL settings. Are you interested in a PR for this?

**Comment by To-om** [comment]
Hi,

Do you know which protocol is used with SSL communication, [TCP transport](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/modules-transport.html) or [HTTP](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/modules-http.html) ?

Currently, Elastic4play uses TCP transport of ElasticSearch (which is deprecated). I've stated to implement HTTP on branch `feature/http` but elastic4s doesn't support XPack on HTTP (cf. https://github.com/sksamuel/elastic4s#x-pack-security)

I'd be happy to accept your PR.

**Comment by srilumpa** [comment]
At first, we configured our cluster to use SSL on both HTTP and TCP transport. For now, we have deactivated SSL on TCP transport to pursue our Cortex upgrade but we have kept it on HTTP.
