### ISSUE TITLE
Allow external authentication on a reverse proxy

### ISSUE THREAD

**Issue by To-om** [TheHive-Project/elastic4play#73]
This feature allow to delegate authentication to a reverse proxy, in front of the application. The user identity is forwarded using HTTP header.
This feature is enabled by adding `auth.method.header = true` in application.conf. Then the name of the header must be set by `auth.header.name = AUTH_USER`

This feature may imply security flaw if an user can contact TheHive directly. He would be able to set the configured header and choose his identity. Before enabling this feature, it is important to be sure that only the reverse proxy can contact the application.

**Comment by zmaktouf** [comment]
Hi, Is this also available for Cortex?

**Comment by To-om** [comment]
yes
